### ISSUE TITLE
Forked version 

### ISSUE THREAD

**Issue by hamnis** [jestan/sbt-app-assembler#1]
Hello.

I have been looking for something like this.
Take a look at my version and see if this is something that you would like to include in your, or if this should remain a fork.

https://github.com/hamnis/sbt-app-assembler

**Comment by hamnis** [comment]
I have published a version of my fork of the plugin to sonatype.

I have set the license to apache license. 

Please let me know if you object.

if I hear nothing within April 7th I will assume that you are OK with me publishing this.

**Comment by hamnis** [comment]
https://oss.sonatype.org/content/repositories/nethamnaberg-1033/

**Comment by jestan** [comment]
@hamnis I just saw this, I have no problem about the license.
